import type { Genre, Movie } from "./types";

/** Fallback when TMDB credentials are not configured */
export const MOCK_GENRES: Genre[] = [
  { id: 28, name: "Action" },
  { id: 18, name: "Drama" },
  { id: 878, name: "Science Fiction" },
  { id: 35, name: "Comedy" },
  { id: 27, name: "Horror" },
  { id: 10749, name: "Romance" },
  { id: 53, name: "Thriller" },
  { id: 16, name: "Animation" },
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: 550,
    title: "Fight Club",
    overview: "An insomniac office worker forms an underground fight club.",
    posterPath: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropPath: null,
    genreIds: [18, 53],
    voteAverage: 8.4,
    releaseDate: "1999-10-15",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, and more intertwine.",
    posterPath: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropPath: null,
    genreIds: [80, 53],
    voteAverage: 8.5,
    releaseDate: "1994-09-10",
  },
  {
    id: 13,
    title: "Forrest Gump",
    overview: "The presidencies of Kennedy and Johnson through the eyes of Forrest.",
    posterPath: "/arw2vcBveWOVZr6pxd9xccxsBZK.jpg",
    backdropPath: null,
    genreIds: [35, 18, 10749],
    voteAverage: 8.5,
    releaseDate: "1994-06-23",
  },
  {
    id: 155,
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime.",
    posterPath: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: null,
    genreIds: [28, 80, 18, 53],
    voteAverage: 8.5,
    releaseDate: "2008-07-18",
  },
  {
    id: 27205,
    title: "Inception",
    overview: "A thief who steals corporate secrets through dream-sharing technology.",
    posterPath: "/9gk7adHYeDvHkC0q9z0pBz7JJAg.jpg",
    backdropPath: null,
    genreIds: [28, 878, 53],
    voteAverage: 8.4,
    releaseDate: "2010-07-16",
  },
  {
    id: 157336,
    title: "Interstellar",
    overview: "Explorers travel through a wormhole in space.",
    posterPath: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropPath: null,
    genreIds: [18, 878],
    voteAverage: 8.4,
    releaseDate: "2014-11-07",
  },
  {
    id: 603,
    title: "The Matrix",
    overview: "A computer hacker learns about the true nature of reality.",
    posterPath: "/f89U3ADr1oiB1s9GkdPOEpPEU04.jpg",
    backdropPath: null,
    genreIds: [28, 878],
    voteAverage: 8.2,
    releaseDate: "1999-03-31",
  },
  {
    id: 496243,
    title: "Parasite",
    overview: "Greed and class discrimination threaten a newly formed symbiotic relationship.",
    posterPath: "/7IiTTgloJzvI1NDYlhxQnziqH0.jpg",
    backdropPath: null,
    genreIds: [35, 18, 53],
    voteAverage: 8.5,
    releaseDate: "2019-05-30",
  },
  {
    id: 346364,
    title: "It",
    overview: "Children in a small town face their fears when a clown returns.",
    posterPath: "/9E2y5Qhyv0IhUxQWfDpfXMYfUqH.jpg",
    backdropPath: null,
    genreIds: [27, 53],
    voteAverage: 7.2,
    releaseDate: "2017-09-06",
  },
  {
    id: 419430,
    title: "Get Out",
    overview: "A young African-American visits his white girlfriend's parents.",
    posterPath: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdropPath: null,
    genreIds: [27, 53, 9648],
    voteAverage: 7.6,
    releaseDate: "2017-02-24",
  },
  {
    id: 106646,
    title: "The Wolf of Wall Street",
    overview: "Based on the true story of Jordan Belfort.",
    posterPath: "/34OGjQb9jNghn75R8ovQoVd1tX7.jpg",
    backdropPath: null,
    genreIds: [80, 18, 35],
    voteAverage: 8.0,
    releaseDate: "2013-12-25",
  },
  {
    id: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "A meek Hobbit begins a journey to destroy the One Ring.",
    posterPath: "/6oom5QYQ2yQTMJIbnvbkBL9aeGv.jpg",
    backdropPath: null,
    genreIds: [12, 14, 28],
    voteAverage: 8.4,
    releaseDate: "2001-12-19",
  },
  {
    id: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    overview: "Raj and Simran fall in love during a European vacation.",
    posterPath: "/2u7uQX8ZudUxr6fQ9e3a4t5NlBm.jpg",
    backdropPath: null,
    genreIds: [18, 10749, 35],
    voteAverage: 8.5,
    releaseDate: "1995-10-20",
  },
  {
    id: 238,
    title: "The Godfather",
    overview: "The aging patriarch of an organized crime dynasty transfers control.",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropPath: null,
    genreIds: [18, 80],
    voteAverage: 8.7,
    releaseDate: "1972-03-14",
  },
  {
    id: 424,
    title: "Schindler's List",
    overview: "Oskar Schindler becomes concerned for his Jewish workforce.",
    posterPath: "/sF1U4EUQS8YHUYjNl3pMGWMQ89S.jpg",
    backdropPath: null,
    genreIds: [18, 36, 10752],
    voteAverage: 8.6,
    releaseDate: "1993-12-15",
  },
  {
    id: 129,
    title: "Spirited Away",
    overview: "A young girl enters a world ruled by gods and spirits.",
    posterPath: "/39wmItIWsg5sZMyRUHLkWBcuFiG.jpg",
    backdropPath: null,
    genreIds: [16, 14, 10751],
    voteAverage: 8.5,
    releaseDate: "2001-07-20",
  },
  {
    id: 324857,
    title: "Spider-Man: Into the Spider-Verse",
    overview: "Teen Miles Morales becomes Spider-Man of his universe.",
    posterPath: "/iiZZdoQ2YBFP0Nae75NqH85jjFr.jpg",
    backdropPath: null,
    genreIds: [16, 28, 12, 878],
    voteAverage: 8.4,
    releaseDate: "2018-12-14",
  },
  {
    id: 862,
    title: "Toy Story",
    overview: "Woody and Buzz Lightyear find their place in Andy's room.",
    posterPath: "/uXDfjJbdP4ijW5hWSBrPrlKpxar.jpg",
    backdropPath: null,
    genreIds: [16, 35, 10751],
    voteAverage: 8.0,
    releaseDate: "1995-11-22",
  },
];
